version: "3.9"
services:
  madlib-website:
    image: arnaudboeglin/madlib-website:latest
    init: true
    ulimits:
      core: -1
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - type: bind
        source: ./cert.crt
        target: /ssl/cert.crt
        read_only: true
      - type: bind
        source: ./cert.key
        target: /ssl/cert.key
        read_only: true
      # for core dumps, configured on host with: echo '/tmp/core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
      - type: bind
        source: /tmp/
        target: /tmp/
    environment:
      - SSL_CERT=/ssl/cert.crt
      - SSL_KEY=/ssl/cert.key
    labels:
      com.datadoghq.ad.check_names: '["madlib-website"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances": '[{"nginx_status_url": "http://%%host%%:%%port%%/"}]'
      com.datadoghq.ad.logs": '[{"source": "madserver", "service": "madlib-website"}]'
