version: "3.9"
services:
  madlib-website:
    image: arnaudboeglin/madlib-website:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - type: bind
        source: ./cert.crt
        target: /ssl/cert.crt
        read_only: true
      - type: bind
        source: ./cert.key
        target: /ssl/cert.key
        read_only: true
    environment:
      - SSL_CERT=/ssl/cert.crt
      - SSL_KEY=/ssl/cert.key
      # - SSL_CA=/ssl/cert.ca-bundle
